import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { fileURLToPath, URL } from 'node:url'
import { resolve } from 'path'

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [vue()], // to process SFC
    build: {
        lib: {
            entry: resolve(__dirname, 'src/index.ts'),
            name: 'sui-vue',
            formats: ['es'], // adding 'umd' requires globals set to every external module
            fileName: format => `sui-vue.${format}.js`,
        },
        rollupOptions: {
            // external modules won't be bundled into your library
            external: ['vue'],
            output: {
                // disable warning on src/index.ts using both default and named export
                exports: 'named',
                globals: {
                    vue: 'Vue'
                },
                assetFileNames: assetInfo => assetInfo.name === 'style.css' ? 'style.min.css' : assetInfo.name
            }
        },
        emptyOutDir: false, // to retain the types folder generated by tsc
    }
})
