export enum Status {
    ACTIVE = 'ACTIVE',
    COMPLETED = 'COMPLETED',
    EXPIRED = 'EXPIRED',
    FAILED = 'FAILED',
    INACTIVE = 'INACTIVE',
    PAID = 'PAID',
    PENDING = 'PENDING',
    REFUNDED = 'REFUNDED',
    APPROVED = 'APPROVED',
    DECLINED = 'DECLINED',
}

export enum Telco {
    AIRTEL = 'AIRTEL',
    EQUITEL = 'EQUITEL',
    FAIBA = 'FAIBA',
    SAFARICOM = 'SAFARICOM',
    TELKOM = 'TELKOM',
}
